# Generated by Django 4.2 on 2023-09-06 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callboard', '0002_advertisement_date_creation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediacontent',
            old_name='file',
            new_name='media_file',
        ),
        migrations.AddField(
            model_name='mediacontent',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
